- name: install ffmpeg
  hosts: talkliketv
  become: True
  gather_facts: yes
  tags:
    - ffmpeg
  roles:
    - role: ffmpeg

- name: install gcp-ops-agent
  hosts: talkliketv
  become: True
  gather_facts: yes
  tags:
    - gcp-ops-agent
  roles:
    - role: gcp-ops-agent

- name: install caddy
  hosts: talkliketv
  become: True
  gather_facts: yes
  tags:
    - caddy
  roles:
    - role: caddy

- name: install talkliketv
  hosts: talkliketv
  become: True
  gather_facts: yes
  tags:
    - talkliketv
  roles:
    - role: talkliketv