---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tltv-deployment
  labels:
    app: tltv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tltv
  template:
    metadata:
      labels:
        app: tltv
    spec:
      containers:
        - name: tltv
          image: token-tltv:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tltv-svc
spec:
  type: NodePort
  selector:
    app: tltv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000