// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/translates/translates.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=internal/mock/translates.go -source=internal/services/translates/translates.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	language "golang.org/x/text/language"
	interfaces "talkliketv.com/tltv/internal/interfaces"
)

// MockTranslateX is a mock of TranslateX interface.
type MockTranslateX struct {
	ctrl     *gomock.Controller
	recorder *MockTranslateXMockRecorder
	isgomock struct{}
}

// MockTranslateXMockRecorder is the mock recorder for MockTranslateX.
type MockTranslateXMockRecorder struct {
	mock *MockTranslateX
}

// NewMockTranslateX creates a new mock instance.
func NewMockTranslateX(ctrl *gomock.Controller) *MockTranslateX {
	mock := &MockTranslateX{ctrl: ctrl}
	mock.recorder = &MockTranslateXMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslateX) EXPECT() *MockTranslateXMockRecorder {
	return m.recorder
}

// CreateTTS mocks base method.
func (m *MockTranslateX) CreateTTS(c context.Context, title interfaces.Title, voice interfaces.Voice, basePath string) ([]interfaces.Phrase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTTS", c, title, voice, basePath)
	ret0, _ := ret[0].([]interfaces.Phrase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTTS indicates an expected call of CreateTTS.
func (mr *MockTranslateXMockRecorder) CreateTTS(c, title, voice, basePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTTS", reflect.TypeOf((*MockTranslateX)(nil).CreateTTS), c, title, voice, basePath)
}

// DetectLanguage mocks base method.
func (m *MockTranslateX) DetectLanguage(c context.Context, phrases []string) (language.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectLanguage", c, phrases)
	ret0, _ := ret[0].(language.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectLanguage indicates an expected call of DetectLanguage.
func (mr *MockTranslateXMockRecorder) DetectLanguage(c, phrases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectLanguage", reflect.TypeOf((*MockTranslateX)(nil).DetectLanguage), c, phrases)
}

// TranslatePhrases mocks base method.
func (m *MockTranslateX) TranslatePhrases(c context.Context, title interfaces.Title, lang interfaces.Language) ([]interfaces.Phrase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslatePhrases", c, title, lang)
	ret0, _ := ret[0].([]interfaces.Phrase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslatePhrases indicates an expected call of TranslatePhrases.
func (mr *MockTranslateXMockRecorder) TranslatePhrases(c, title, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslatePhrases", reflect.TypeOf((*MockTranslateX)(nil).TranslatePhrases), c, title, lang)
}
